version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building the application"
      - mkdir -p build
      # Only copy relevant files to the build directory
      - cp index.html build/
      - cp -r styles.css script.js build/

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
  s3:
    bucket: thisismybucket12345000
    path: todo-app-builds
