version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building the application"
artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
  s3:
    bucket: thisismybucket12345000
    path: todo-app-builds
